name: Build cyrOS with cyrDE ISO

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: '1.0'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Use /mnt for Temporary Storage
        run: |
          sudo mkdir -p /mnt/temp
          sudo chmod 777 /mnt/temp

      - name: Build CyrOS ISO
        run: |
          docker run --rm --privileged \
            -v "$GITHUB_WORKSPACE:/work" \
            -v "/mnt/temp:/tmp" \
            archlinux:latest /bin/bash -c "
              pacman -Sy --noconfirm archiso wget &&
              wget https://raw.githubusercontent.com/ParsaAslaniYC/ParsaAslaniYC/refs/heads/master/moonlight.balens &&
              wget https://raw.githubusercontent.com/ParsaAslaniYC/ParsaAslaniYC/refs/heads/master/balens &&
              wget https://raw.githubusercontent.com/ParsaAslaniYC/ParsaAslaniYC/refs/heads/master/mlos.cpp &&
              cp mlos.cpp /work/empty.cpp &&
              chmod +x balens &&
              ./balens
            "

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: cyros-iso
          path: /mnt/temp/out/*.iso
