name: Build cyrOS with cyrDE ISO

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'main'


jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Use /mnt for Temporary Storage
        run: |
          sudo mkdir -p /mnt/temp
          sudo chmod 777 /mnt/temp

      - name: Build CyrOS ISO
        run: |
          docker run --rm --privileged \
            -v "$GITHUB_WORKSPACE:/work" \
            -v "/mnt/temp:/tmp" \
            agners/archlinuxarm /bin/bash -c "
              pacman -Syu --noconfirm &&
              pacman -Sy --noconfirm wget grub git make &&
              git clone https://github.com/openai-ae/cyrINSTALLER_cfg cmares &&
              git clone https://github.com/JackMyers001/archiso-aarch64.git &&
              cd archiso-aarch64 &&
              make install &&
              cd .. &&
              mv cmares/* airootfs/ &&
              mkarchiso -v -w /tmp/work -o /tmp/out /work
            "

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: cyros-iso
          path: /mnt/temp/out/*.iso
